### ISSUE TITLE
Pytesseract image_to_pdf_or_hocr function throws an error.

### ISSUE THREAD

**Issue by prameshbajra** [bweigel/aws-lambda-tesseract-layer#28]
First of all, 
Thank you for making our lives easier by developing this. It helped a lot.

Other functions that `pytesseract` offers like: `image_to_string`, `image_to_data`  works well without any hiccups.

But, when I try to use image_to_pdf_or_hocr like this:
```python
pdf = pytesseract.image_to_pdf_or_hocr(f'/tmp/{file_name}/{page.number}.png', extension='pdf')
```

it does not work and throws error like:

```
Traceback (most recent call last):
File "/var/task/helpers/ocr_helper.py", line 36, in save_searchable_pdf
f'/tmp/{file_name}/{page.number}.png', extension='pdf')
File "/var/task/pytesseract/pytesseract.py", line 432, in image_to_pdf_or_hocr
return run_and_get_output(*args)
File "/var/task/pytesseract/pytesseract.py", line 289, in run_and_get_output
with open(filename, 'rb') as output_file:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tess_6_hu78b0.pdf'
```

1. It says that the file `tess_6_hu78b0.pdf` does not exist. What does this mean? I have no file with `tess_6_hu78b0` name to begin with.
2. The path that I am passing to `image_to_pdf_or_hocr` function is 100% correct and an image is present there. I have confirmed and the same thing works on my local.

----

I found somewhere that I needed to install libtesseract-dev too. Hence, I modified my dockerfile as:
```
FROM lambci/lambda:build-python3.6
RUN sudo apt install tesseract-ocr
RUN sudo apt install libtesseract-dev
```
but unfortunately this too did not work.

<b>Can someone please help me out on this? Thank you.</b>

**Comment by prameshbajra** [comment]
Solution found:
I wrote the solution in StackOverflow.

https://stackoverflow.com/a/66656261/5753035

Hope this helps future answer seekers.
